# Generated by Django 6.0.7 on 2026-07-18 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='image',
            field=models.ImageField(blank=True, default='listings/default.jpg', null=True, upload_to='listings/'),
        ),
    ]
